import type { Metadata } from "next";
import { Providers } from "./provider";
import { ReactNode } from "react";
import { NavBar } from "@/components/Navbar";
import { VStack } from "@chakra-ui/react";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: ReactNode }) {
  return (
    <html lang="en">
      <body>
        <Providers>
          <VStack padding={10}>
            <NavBar />
            {children}
          </VStack>
        </Providers>
      </body>
    </html>
  );
}
